In [2]:
import numpy as np

### задача 1

In [10]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [11]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = np.mean(a)

In [13]:
mean_a

5.2

### задача №2

In [14]:
a_centered = a - mean_a

In [15]:
a_centered

array([[-4.2,  0.8],
       [-3.2,  2.8],
       [-2.2,  5.8],
       [-2.2,  4.8],
       [-4.2,  1.8]])

### задача 3

In [17]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [18]:
a_centered_sp

-43.199999999999996

In [20]:
a_centered_sp / 5 - 1

-9.639999999999999

# 2й вариант дз из 3х заданий

## пишу 2й вариан так как возможно в 1 закралась ошибка

In [21]:
b = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [22]:
mean_b = np.mean(b, axis=0)

#### именно в этом месте ошибка скорей всего в 1 вариане.
#### и я не понимаю как правильно ставить axis=.... нашел это в документации там = 0 или 1 решил поставить 0, но не знаю парвильно ли?

In [23]:
mean_b

array([2. , 8.4])

In [24]:
b_centered = b - mean_b

In [25]:
b_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
b_centered_sp = b_centered.T[0] @ b_centered.T[1]

In [27]:
b_centered_sp

8.0

### снова 2 варианта решения в отличии от 1 случая где возможент только 1.
### исходя из условий к первому заданию N= колличеству строк(5), но есть метод shape который показывает размерность масива потому 2 варианта решения и я их считаю разными из за того что используя shape второе число стало 3. и я не пойму почему? когда первое число можно считать округленым из первого варианта решения без shape

In [28]:
b_centered_sp / 5 - 1

0.6000000000000001

In [32]:
b_centered.shape

(5, 2)

In [33]:
b_centered_sp / b_centered.shape - 1

array([0.6, 3. ])

##### 4 задание хочу сделать отдельно возможно без проверки когда пойму что правильно, а что нет в первых трех

# PANDAS

## Задание 1

In [38]:
import pandas as pd

In [40]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                       'author_name':['Тургенев','Чехов','Островский']},
                      columns=['author_id', 'author_name'])

In [41]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [42]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]})

In [43]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [44]:
authors_price = pd.merge(authors, book, on = 'author_id')

In [45]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [46]:
top5 = authors_price.nlargest(5, 'price')

In [47]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [51]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})

In [53]:
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

In [54]:
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

## Задание 5

In [62]:
?pd.pivot_table

In [55]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [56]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [57]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)

In [58]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [59]:
book_info.to_pickle('book_info.pkl')

In [60]:
book_info2 = pd.read_pickle('book_info.pkl')

In [61]:
book_info.equals(book_info2)

True